#服务器配置
server:
  port: 8080
#token加密密钥
token:
  secret: "token_photoshare"
#mssql数据库配置
mssql:
  server: "112.74.48.21"
  port: 63354
  user: "sa"
  password: "Lkl888888"
  database: "photoshare"

#redis配置
redis:
  user:
    address: "112.74.48.21:6379"
    dbnum: 0
    password: ""
  sms:
    address: "112.74.48.21:6379"
    dbnum: 1
    password: ""

#静态资源配置
static:
  publishimgpath: "./image/uploadimg/"
  allowimg: "png,jpg"
  maxuploadimgsize: 104857600
