@host = http://localhost:8080
#@host = http://www.onlinemusic.top

###注册接口
POST {{host}}/user HTTP/1.1
Content-Type: application/json
Cookie: token=1023-5ca282a436d0c87e532fbc9a3e8e737f-1608653320

{
    "Name" : "临时工",
    "Headimg" : "",
    "Phone" : "17854276299",
    "City" : 0,
    "Brithday" : "2020-11-11T00:00:00Z",
    "Ismale" : true,
    "Password" : "test123"
}

###登录接口
POST {{host}}/user/login HTTP/1.1

{
    "Id" : 1023,
    "Password" : "test123"
}

###获取用户信息接口
GET {{host}}/user/info HTTP/1.1
Cookie: token=1023-fffffac108574ededae36bc5fc1d6885-1608824850


###获取注册码接口
GET {{host}}/user/code HTTP/1.1


###第三方回调注册码接口
GET {{host}}/user/callback?mobile=17854276064&content=34 HTTP/1.1


###获取注册码信息接口
GET {{host}}/user/code/34 HTTP/1.1